KinKal/KKTrk.hh
KinKal/KTMIsect.hh
UnitTests/FitTest_unit.cc
UnitTests/HitTest_unit.cc

(Helping out Sophie and Richie)
A few fixes to ensure that the code builds without warnings and template errors on mu2egpvm01.
While my local build environment (gcc 9.3.0) was successfully able to deduce that e.g.
```
auto iemp = effects_.emplace(new KKMHit(*hit,reftraj));
```
meant
```
auto iemp = effects_.emplace(new KKMHit<KTRAJ>(*hit,reftraj));
```
gcc 8.2.0 on mu2egpvm could not deduce this, so I changed two lines to explicitly state the template argument `KTRAJ` to avoid template errors.
I also added an include to avoid an incomplete type error, and changed `int` types in loops to `size_t` where needed to avoid type mismatch warnings.
Builds successfully with this UPS environment on mu2egpvm01:
```
Active ups products:
fftw              v3_3_8a         -f Linux64bit+3.10-2.17 -q …
```

Fixes needed for successful build on mu2egpvm with gcc ~8.2.0

---

KinKal/IPHelix.cc
KinKal/IPHelix.hh
KinKal/TPoca_IPHelix.cc
UnitTests/BFieldTest.hh
UnitTests/FitTest.hh
UnitTests/HitTest.hh
UnitTests/IPHelixHitTest_unit.cc
UnitTests/KTrajDerivs_test.hh
UnitTests/LHelixHitTest_unit.cc
UnitTests/PKTrajTest.hh
UnitTests/TPocaTest.hh

The IPHelix `direction` method wasn't taking into account the rotation, so I fixed that (I needed to add `_l2g`). Now the output ROOT filenames of the unit tests will contain the name of the specialization, to avoid confusion. Also, now it is possible to pass the numerical derivative intervals to `HitTest` as an argument.

Fixed IPHelix rotation, added name of the specialization to unit tests ROOT files

---

KinKal/CentralHelix.cc
KinKal/CentralHelix.hh

This version implements a preliminary version of the CentralHelix specialization. The `dPardX` derivatives and the `z0` and `t0` derivatives for dPardM are missing.

Preliminary version of derivatives for CentralHelix

---

.ci-setup.sh
.travis-before-install.sh
.travis-script.sh
.travis.yml
CMakeLists.txt
KinKal/CMakeLists.txt
README.md
UnitTests/CMakeLists.txt

I noticed @soleti added Travis CI to this repository, which is a very good thing!
I made this a while back in June but never got around to proposing it. It executes a KinKal build and tests in an SLF7 docker container with the mu2e environment pulled from CVMFS.
One build takes about 3-4 minutes. Here is an example: https://travis-ci.org/github/ryuwd/KinKal/builds/703239979
It's not ready to merge as is, as there will be conflicts with the current `.travis.yml`, and I suspect tweaks will be necessary. It should be possible to adapt this job to also execute in parallel to the MacOS tests.

Travis CI - combined macOS and linux CI testing

---

CMakeLists.txt
KinKal/CMakeLists.txt
MatEnv/CMakeLists.txt
UnitTests/CMakeLists.txt

- Enforces two build types: `Release` and `Debug`
- `prof`, `profile` is corrected to `Release`
- If no `CMAKE_BUILD_TYPE` is specified, default to `Release`
- Got rid of dated `CMAKE_CXX_FLAGS` usage, which is no longer recommended
- Compiler options are set using cross-platform friendly `add_compile_options` function
- Package directories have explicit lists of `*.cc` files to make sure CMake detects when new `*.cc` files are added
- file(GLOB ...) is discouraged by CMake developers
- Easy to regenerate these using `ls -1 *.cc` and copy-paste
- Comments elaborate on this

CMake housekeeping

---

.clang-tidy
CMakeLists.txt
Tests/CMakeLists.txt

- install all `*.hh` files preserving directory structure into `CMAKE_INSTALL_PREFIX/include/KinKal/<MatEnv/General/Fit/..>/<headerfile>.hh`
- option to create a `clang-tidy` target (default off). Can be made to work on `macOS` like this:
```
brew install llvm
ln -s "$(brew --prefix llvm)/bin/clang-tidy" "/usr/local/bin/clang-tidy"
ln -s "$(brew --prefix llvm)/share/clang/run-clang-tidy.py" "/usr/local/bin/run-clang-tidy"
mkdir build && cd build
cmake ../KinKal -DENABLE_CLANG_TIDY=ON
make tidy
```
- a release of KinKal can be installed to a directory like this:
```
mkdir build && cd build
cmake ../KinKal -DCMAKE_INSTALL_PREFIX=path/to/install/location
make -j8
make install
```

Install headers + clang-tidy

---

CMakeLists.txt

Removes dependency on `run-clang-tidy`. Takes advantage of native cmake support

use native cmake support for clang tidy rather than run-clang-tidy

---

CMakeLists.txt

Stops `git describe` from ignoring the `v0.1.0` tag.

use unannotated tags for git describe

---

.github/workflows/build-test.yml
CMakeLists.txt
README.md

Hello again!
Hope all is well (and a very belated happy new year!) Following my last PR I thought I'd clean up a bit and add a couple of small adjustments for completeness:
Logs have colour enabled now (as Travis did) and are easier to read
Clang-tidy runs now as an extra step
Example output here: 
https://github.com/ryuwd/KinKal/runs/1717884942?check_suite_focus=true
Clang-tidy runs in every job after a successful build + test run. You can see the log output by expanding the "Run clang-tidy" item: 
Warnings from clang-tidy don't cause checks to fail.

Clang-Tidy + colour in log files

---

.clang-tidy
.github/workflows/build-test.yml
CMakeLists.txt

- Clang-tidy now only runs on Linux Release builds (saves runner minutes)
- conda environments are cached to also save time
- `with:fetch-depth: 0` added to see if that makes release tags available in the CI builds
- clang-tidy fix suggestions are added as review comments to pull requests (see https://github.com/ryuwd/KinKal/pull/41#pullrequestreview-616798131)
I attempted to enable `-Wshadow` but this revealed a few occurences of shadowing in `MatEnv`, `Detector` packages, so I left that out

actions cleanup

---

.github/workflows/build-test.yml
CMakeLists.txt
README.md
Tests/CMakeLists.txt

A nice code tool I've been looking into recently. Unit test coverage % is calculated using `gcov` / `llvm-coverage gcov` and coverage flags in gcc or clang (depending on platform). Test coverage tells you which lines of code are covered by unit test cases, and which are missed
CI job also reports test coverage by uploading `gcovr` (`pip install gcovr`) generated reports to codecov.io (needs signup at https://codecov.io/gh - free)
Example PR: https://github.com/ryuwd/KinKal/pull/44#issuecomment-831080534
Example codecov report: https://codecov.io/gh/ryuwd/KinKal/tree/85a742f909846908d9bad62739703416600456ea
`make coverage` prints the coverage report in the terminal (requires `-DCOVERAGE=ON` to be passed to `cmake` + a debug build)

Unit test coverage

---

Detector/ElementXing.hh
Detector/Hit.hh
Fit/BFieldEffect.hh
Fit/CMakeLists.txt
Fit/Config.cc
Fit/Config.hh
Fit/Effect.hh
Fit/HitConstraint.hh
Fit/Material.hh
Fit/MetaIterConfig.cc
Fit/MetaIterConfig.hh
Fit/Track.hh
Fit/TrackEnd.hh
General/BFieldMap.hh
General/TimeRange.cc
General/TimeRange.hh
Tests/BFieldMapTest.hh
Tests/FitTest.hh
Tests/ToyMC.hh
Trajectory/PiecewiseTrajectory.hh

Fix bug with stale configuration cache when extending.  Enforce strict time ordering in TimeRange.  Eliminate 'time buffers' where possible.

Configuration and TimeRange fixes

---

.gitignore
MatEnv/CMakeLists.txt
MatEnv/ELossDistributions.cc
MatEnv/ELossDistributions.hh
Tests/CMakeLists.txt
Tests/ELossDists_unit.cc
Tests/MoyalDist_unit.cc

The methods have been added in a new file named ELossDistributions.cc(hh). This replaces the MoyalDist.cc(hh) file. The Moyal method was left untouched and only the Bremms class was added. It seemed reasonable to keep all distributions and random number sampling at a single place. 
A unit test was also added to plot both types of energy losses through a material of a certain thickness.

Adding in sampling method for Bremsstrahlung energy loss

---

.github/workflows/build-test.yml

I noticed the CI was hanging indefinitely on the setup steps (and none of the build steps). fixes/replaces a broken conda installation step in the CI container

fix broken CI step (?)

---

CMakeLists.txt

Enable c++20 this is done unconditionally.  Ideally it should test on the root configuration and decided on the c++ standard based on that.

enable c++20

---

CMakeLists.txt
Examples/BFieldInfo.hh
Examples/MaterialInfo.hh
Examples/ParticleTrajectoryInfo.hh
General/FitData.hh
Trajectory/KinematicLine.hh

For FitData, I think the warning is triggered because the constructor with a rhs and a bool has a default for the bool, so the constructor acts like a copy constructor.  The rest should be straightforward

Rule3 231110

---

CMakeLists.txt

When running the cmake install under spack, the *.h was not being installed, this should fix it.  The UPS install was always correct since it is done with a separate script.

also install *.h

---

Geometry/Intersect.hh
Geometry/ParticleTrajectoryIntersect.hh

This fixes an infinite loop problem when a trajectory approaches parabolically to a surface. It also improves the search for the correct particle trajectory segment when intersecting.

Add intersection convergence testing

---

Examples/StrawMaterial.hh
MatEnv/DetMaterial.hh
MatEnv/MatDBInfo.cc
MatEnv/MatDBInfo.hh
MatEnv/MaterialInfo.hh
Tests/MatEnv_unit.cc
Tests/ToyMC.hh

Changed matdbinfo.findDetMaterial to return shared pointer instead of raw pointer.

MatEnv Change

---

Detector/ElementXing.hh
Detector/Hit.hh
Detector/ParameterHit.hh
Detector/ResidualHit.hh
Examples/ScintHit.hh
Examples/SimpleWireHit.hh
Examples/StrawXing.hh
Fit/Domain.hh
Fit/DomainWall.hh
Fit/Effect.hh
Fit/Material.hh
Fit/Measurement.hh
Fit/Track.hh
General/CMakeLists.txt
General/CloneContext.cc
General/CloneContext.hh
Trajectory/ClosestApproach.hh
Trajectory/PiecewiseTrajectory.hh

This PR implements a copy-constructor for the `Track<>` class template. Track objects contain references to stateful members in the form of "hits," "element crossings," and "effects," the types of which subclass `KinKal`-defined bases, and which may contain references to each other. The construction of an equivalent, but independent and consistent `Track<>` thus requires reinstantiation of the full relationship graph among its members, the struture of which is defined by the subclass implementations. This is achieved via a recursive, memoized cloning scheme, which requires all track members to provide a reinstantiation (`clone()`) method, which should make use of a common reallocation record (`CloneContext`) to ensure that each graph node is only reallocated once; but this simple …

Implement Track<> copy-constructor and backing graph-copy infrastructure

---

Detector/ElementXing.hh
Examples/StrawXing.hh
Fit/Domain.hh
Fit/Status.hh
Fit/Track.hh
General/TimeRange.hh
Tests/FitTest.hh
Trajectory/PiecewiseTrajectory.hh

This includes the updates to support cloning, as well as some subsequent fixes.

Support for regrowing fits from seeds.

---

Detector/ElementXing.hh
Detector/Residual.hh
Detector/ResidualHit.hh
Examples/ScintHit.hh
Examples/SimpleWireHit.hh
Fit/Material.hh
Fit/Track.hh
Trajectory/LoopHelix.cc
Trajectory/PiecewiseTrajectory.hh

This PR forces phi0 parameter synchronization when appending pieces to a piecetraj. It also softens the failure of an unbiased residual calculation from an exception to an error flag. Some comments are clarified.

Regrow fixes
